### ISSUE TITLE
Correct Lennard-Jones Potential

### ISSUE THREAD

**Issue by cortner** [libAtoms/JuLIP.jl#79]
@gideonsimpson

In light of #78  and. #76  I now feel I should change the LJ potential to be defined as
```
 2 * ( r^(-12) - r^(-6) )
```
agreed?

**Comment by gideonsimpson** [comment]
I completely disagree.  LJ is typically presented as in https://en.wikipedia.org/wiki/Lennard-Jones_potential.  It has that form in LAMMPS, OpenMM, and NAMD.  Whether to use the sigma or equilibrium bond length as the second parameter (after the epsilon refactor), is a separate issue, on which I am agnostic.

Regarding what was discussed in #78 , the issue is that LAMMPS made a design decision that when using lj units, all extensive quantities (i.e., the total energy), are normalized by the number of atoms.  

But this suggests there's an issue with the way energy is calculated in ASE/JuLIP.  For pair potentials, is it doing a sum over I < J, or is it summing over everything?  Summing over everything is obviously wasteful, and also double counts.

**Comment by gabor1** [comment]
I agree that there is already a problem in the leterature about the factor of 4 or 1, let's not introdece 2 as well .. and the majority of people do include the factor of 4. 

Double counting is bad. 

-- Gábor

**Comment by cortner** [comment]
Ok I will change how pair potentials are interpreted and fix LJ as you suggest

**Comment by gideonsimpson** [comment]
So what is the actual form of it now?  I get completely different results for:
``
lj = LennardJones(r0=2.^(1./6.), e0=1.) * HS(2.5)
``
and
``
lj = (@analytic r -> 4*((1/r)^12 - (1/r)^6)) * HS(2.5)
``

**Comment by cortner** [comment]
First of all, don't use `HS`, it creates a discontinuous potential. Use `C0Shift` for a continuous potential and `C1Shift` for a C^{1,1} regular potential.

Secondly, I thought we agreed on `4 * ( r^(-12) - r^(-6) )`, there is no factor 2 anymore, so what you want is 
```
lj = LennardJones() * C0Shift(2.5)
```
This should equivalent to 
```
lj = (@analytic r -> 4*((1/r)^12 - (1/r)^6)) * C0Shift(2.5)
```

**Comment by gideonsimpson** [comment]
What about the epsilon and sigma (or req) parameters?

**Comment by cortner** [comment]
THey are optional parameters

**Comment by gideonsimpson** [comment]
Ok, so it works for me, as expected, when I don't pass parameters.

**Comment by cortner** [comment]
```
LennardJones() == LennardJones(e0=1.0, r0=1.0)
```
I can rename `r0 = \sigma` if that would help

**Comment by gabor1** [comment]
Sigma is more standard. It would be nice if there was an alternative option that allowed one to specify the potential minimum , and also another that allowed to specify the fcc lattice constant

-- Gábor

**Comment by cortner** [comment]
that's no problem - I can implement that.

**Comment by gideonsimpson** [comment]
@cortner sigma and r0 are not the same - see https://en.wikipedia.org/wiki/Lennard-Jones_potential

**Comment by gabor1** [comment]
I think he knows, that's why I suggested that there should be 3 types of initialization for the length scale parameter, sigma, r0 (potential minimum) and a0 (fcc lattice constant)

-- Gábor

**Comment by cortner** [comment]
please check latest master. 
```
using JuLIP, JuLIP.Potentials
?LennardJones
```
and see whether this works for you now? (I haven't tested extensively, just let me know if you run into another bug)
